### ISSUE TITLE
creat pipelineState error using in Agility SDK

### ISSUE THREAD

**Issue by mapmapbear** [NVIDIA-RTX/NRI#94]
### Tested versions
The latest master branch
### System information
Win11 22H2
OS Version 22621.4169
### Agility SDK Version
614
### Issue description
PipelineState creation error only occurs when using the Agility SDK
When I checked Stream, I found that the desc of depthstencilFormat was unknown. I'm not sure if this is related
### Debug Out
![image](https://github.com/user-attachments/assets/951028c8-0626-447d-8c32-2b7c817a26fc)
![image](https://github.com/user-attachments/assets/36b921ba-8839-4e96-ad8a-1792d9d485cf)

**Comment by dzhdanNV** [comment]
Most likely you haven't fully enabled AgilitySDK in the samples. You should not only enable it in Cmake, but also uncomment `#include "NRIAgilitySDK.h` in `SampleBase.cpp`. I will fix it.

**Comment by mapmapbear** [comment]
> Most likely you haven't fully enabled AgilitySDK in the samples. You should not only enable it in Cmake, but also uncomment `#include "NRIAgilitySDK.h` in `SampleBase.cpp`. I will fix it.
I have noticed this issue, but is it normal for there to be symbol repetition?

**Comment by mapmapbear** [comment]
> Most likely you haven't fully enabled AgilitySDK in the samples. You should not only enable it in Cmake, but also uncomment `#include "NRIAgilitySDK.h` in `SampleBase.cpp`. I will fix it.

I have noticed this issue. I have tried, but it has led to the problem of duplicate definitions of agilitySDK symbols

**Comment by mapmapbear** [comment]
> Most likely you haven't fully enabled AgilitySDK in the samples. You should not only enable it in Cmake, but also uncomment `#include "NRIAgilitySDK.h` in `SampleBase.cpp`. I will fix it.

I tried to introduce a symbolic statement(__declspec(dllexport)), and he succeeded. answer！thank you

**Comment by dzhdanNV** [comment]
I have just updated NRI samples and NRD sample with all dependencies. Now NRI Framework has `NRI_ENABLE_AGILITY_SDK_SUPPORT` Cmake option which just enables Agility SDK support, but it doesn't touch `NRI_AGILITY_*` settings from `NRI`. These settings needs to be either respected or changed to point to an unpacked Agility SDK folder.

**Comment by mapmapbear** [comment]
> I have just updated NRI samples and NRD sample with all dependencies. Now NRI Framework has `NRI_ENABLE_AGILITY_SDK_SUPPORT` Cmake option which just enables Agility SDK support, but it doesn't touch `NRI_AGILITY_*` settings from `NRI`. These settings needs to be either respected or changed to point to an unpacked Agility SDK folder.

I tested your latest submission and it was successful👏

**Comment by dzhdanNV** [comment]
Closing? ;)
